version: '3.1'

services:
  minimal-flask:
    container_name: flask
    build:
      context: .
    ports:
      - "4001:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_APP=app
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'employees'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mysql-server-4000
    ports:
      - "4002:3306"
    expose:
      - '4002'


